version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
#  backend:
#    build: ./backend
#    environment:
#      DATABASE_URL: postgres://app:secret@db:5432/appdb
#      JWT_SECRET: supersecret_change_me
#      ACCESS_TOKEN_EXP: 900 # 15 minutes
#      REFRESH_TOKEN_EXP: 604800 # 7 days
#    depends_on:
#      - db
#    ports:
#      - '4000:4000'
#  frontend:
#    build: ./frontend
#    ports:
#      - '3000:3000'
#    environment:
#     NEXT_PUBLIC_API_URL: http://localhost:5000
#    depends_on:
#      - backend
volumes:
  db-data: